### ISSUE TITLE
Concat of infinite streams loses the second stream

### ISSUE THREAD

**Issue by Janiczek** [naddeoa/stream#2]
Let's say I want to get all the multiples of 2 and 3 that are less than 10. This is my (naive?) try to do that [(Ellie)](https://ellie-app.com/RC9fvj7Fa1/0).

```elm
module Main exposing (main)

import Html exposing (Html)
import Stream exposing (Stream)

main : Html msg
main = result |> toString |> Html.text

twos : Stream Int
twos = Stream.iterate 0 ((+) 2)

threes : Stream Int
threes = Stream.iterate 0 ((+) 3)

both : Stream Int
both = Stream.concat twos threes

result : List Int
result =
    both
        |> Stream.takeWhile (\x -> x < 10)
        |> Stream.toList
```

It returns `[0,2,4,6,8]`, ie. no values from the second stream (multiples of 3).
I don't know whether the `concat` implementation is to be fixed, or something like `interleave` function is to be added... ¯\_(ツ)_/¯

**Comment by naddeoa** [comment]
Hey!

Yeah I think this is what I would expect from concat right now. The entire first stream needs to be empty before the second stream will start being used. The implication here is that you probably shouldn't be using infinite streams in concats unless you want to leverage that property in some way. The closest thing in the library right now to what you want is probably going to be `zip`. You're right that a new thing is required for the behavior that you want. I looked up `interleave` in Clojure since I trust that community and this is the behavior.

```clojure
(interleave [1 2 3] [:a :b :c] ["a" "b" "c"] )
(1 :a "a" 2 :b "b" 3 :c "c")
```

That seems like exactly how interleave should behave so it seems like a pretty good name. The implementation is probably going to look a lot like the `flatten` feature that was just requested in https://github.com/naddeoa/stream/issues/1. In `flatten`, a stream of streams is held and one by one the head stream is pulled out and items are used from it. In `interleave` the difference will be that the head stream is only used once and then placed at the tail of the stream of streams instead, probably with `concat`. 

Is it fair to consider this a request for the missing `interleave` function?

**Comment by Janiczek** [comment]
Yes! You're the best :)

**Comment by naddeoa** [comment]
Check it out: https://github.com/naddeoa/stream/commit/f3917faecdfa4c905d57fa82c5eee8dbc2b39ef8

The only issue I see here is that it doesn't take a `Stream (Stream a)`, it takes a `List (Stream a)`. Its pretty tricky to do it with the former over the later. Let me know what you think.

**Comment by Janiczek** [comment]
To me that looks good! I only needed `List (Stream a)` anyway :)

**Comment by naddeoa** [comment]
All done. Let me know if you have any issues.
